import { Session } from 'next-auth';
import { UserProfile } from '@/types/profile';
import { rehostGoogleProfileImage } from '@/lib/firebase/storage';

/**
 * New User Service
 * Handles detection and orchestration of new user onboarding flow
 */

interface CreateDefaultProfileParams {
  session: Session;
}

interface DefaultProfileResult {
  profile: UserProfile;
  isNewUser: boolean;
}

/**
 * Detects if this is a new user based on session flags
 */
export function isNewUser(session: Session | null): boolean {
  if (!session?.user) return false;
  
  // Check NextAuth's new user flag (set during first sign-in)
  return (session as any).isNewUser === true;
}


/**
 * Creates a default profile for new users with auto-generated social media
 */
export function createDefaultProfile({ session }: CreateDefaultProfileParams): DefaultProfileResult {
  if (!session?.user) {
    throw new Error('Session required to create default profile');
  }

  const profile: UserProfile = {
    userId: session.user.id || '',
    name: session.user.name || '',
    bio: '', // Will be generated by AI service
    profileImage: session.user.image || '',
    backgroundImage: '', // Will be generated by AI service
    lastUpdated: Date.now(),
    contactChannels: {
      phoneInfo: {
        internationalPhone: '',
        nationalPhone: '',
        userConfirmed: false
      },
      email: {
        email: session.user.email || '',
        userConfirmed: !!session.user.email
      },
      // Social profiles will be created by BioAndSocialGenerationService
      facebook: { username: '', url: '', userConfirmed: false },
      instagram: { username: '', url: '', userConfirmed: false },
      x: { username: '', url: '', userConfirmed: false },
      linkedin: { username: '', url: '', userConfirmed: false },
      snapchat: { username: '', url: '', userConfirmed: false },
      whatsapp: { username: '', url: '', userConfirmed: false },
      telegram: { username: '', url: '', userConfirmed: false },
      wechat: { username: '', url: '', userConfirmed: false }
    }
    // Removed aiGeneration field - should not be saved to Firestore
  };

  return {
    profile,
    isNewUser: true
  };
}

